#ifndef QVESMODELDELEGATE_GLOBAL_H
#define QVESMODELDELEGATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QVESMODELDELEGATE_LIBRARY)
#  define QVESMODELDELEGATESHARED_EXPORT Q_DECL_EXPORT
#else
#  define QVESMODELDELEGATESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QVESMODELDELEGATE_GLOBAL_H
